from django.core.management.base import BaseCommand
from wallet.models import Currency

class Command(BaseCommand):
    help = 'Заполняет базу данных валютами'

    def handle(self, *args, **options):
        currencies_data = [
            {'name': 'United States Dollar', 'code': 'USD', 'exchange_rate': 1.0},
            {'name': 'Euro', 'code': 'EUR', 'exchange_rate': 0.85},
            {'name': 'Japanese Yen', 'code': 'JPY', 'exchange_rate': 110.0},
            {'name': 'British Pound', 'code': 'GBP', 'exchange_rate': 0.75},
            {'name': 'Australian Dollar', 'code': 'AUD', 'exchange_rate': 1.35},
            {'name': 'Canadian Dollar', 'code': 'CAD', 'exchange_rate': 1.25},
            {'name': 'Swiss Franc', 'code': 'CHF', 'exchange_rate': 0.92},
            {'name': 'Chinese Yuan Renminbi', 'code': 'CNY', 'exchange_rate': 6.46},
            {'name': 'Swedish Krona', 'code': 'SEK', 'exchange_rate': 8.8},
            {'name': 'New Zealand Dollar', 'code': 'NZD', 'exchange_rate': 1.45},
            {'name': 'South Korean Won', 'code': 'KRW', 'exchange_rate': 1200.0},
            {'name': 'Singapore Dollar', 'code': 'SGD', 'exchange_rate': 1.33},
            {'name': 'Hong Kong Dollar', 'code': 'HKD', 'exchange_rate': 7.8},
            {'name': 'Norwegian Krone', 'code': 'NOK', 'exchange_rate': 9.0},
            {'name': 'Mexican Peso', 'code': 'MXN', 'exchange_rate': 20.0},
            {'name': 'Indian Rupee', 'code': 'INR', 'exchange_rate': 75.0},
            {'name': 'Russian Ruble', 'code': 'RUB', 'exchange_rate': 80.0},
            {'name': 'Brazilian Real', 'code': 'BRL', 'exchange_rate': 5.2},
            {'name': 'South African Rand', 'code': 'ZAR', 'exchange_rate': 14.0},
            {'name': 'Turkish Lira', 'code': 'TRY', 'exchange_rate': 8.7},
            {'name': 'Indonesian Rupiah', 'code': 'IDR', 'exchange_rate': 14000.0},
            {'name': 'Saudi Riyal', 'code': 'SAR', 'exchange_rate': 3.75},
            {'name': 'Thai Baht', 'code': 'THB', 'exchange_rate': 32.0},
            {'name': 'Polish Złoty', 'code': 'PLN', 'exchange_rate': 3.85},
            {'name': 'Israeli Shekel', 'code': 'ILS', 'exchange_rate': 3.25},
            {'name': 'Iranian Rial', 'code': 'IRR', 'exchange_rate': 42105.0},
            {'name': 'Czech Koruna', 'code': 'CZK', 'exchange_rate': 22.0},
            {'name': 'Ukrainian Hryvnia', 'code': 'UAH', 'exchange_rate': 27.0},
            {'name': 'Romanian Leu', 'code': 'RON', 'exchange_rate': 4.2},
            {'name': 'Kuwaiti Dinar', 'code': 'KWD', 'exchange_rate': 0.3},
            {'name': 'Danish Krone', 'code': 'DKK', 'exchange_rate': 6.0},
            {'name': 'Malaysian Ringgit', 'code': 'MYR', 'exchange_rate': 4.2},
            {'name': 'Argentine Peso', 'code': 'ARS', 'exchange_rate': 100.0},
            {'name': 'Nigerian Naira', 'code': 'NGN', 'exchange_rate': 400.0},
            {'name': 'Belarusian Ruble', 'code': 'BYN', 'exchange_rate': 2.5},
            {'name': 'Hungarian Forint', 'code': 'HUF', 'exchange_rate': 300.0},
            {'name': 'Venezuelan Bolívar', 'code': 'VES', 'exchange_rate': 2000000.0},
            {'name': 'Colombian Peso', 'code': 'COP', 'exchange_rate': 4000.0},
            {'name': 'Uruguayan Peso', 'code': 'UYU', 'exchange_rate': 45.0},
            {'name': 'Icelandic Króna', 'code': 'ISK', 'exchange_rate': 130.0},
            {'name': 'Egyptian Pound', 'code': 'EGP', 'exchange_rate': 15.7},
            {'name': 'Serbian Dinar', 'code': 'RSD', 'exchange_rate': 100.0},
            {'name': 'Jordanian Dinar', 'code': 'JOD', 'exchange_rate': 0.71},
            {'name': 'Dominican Peso', 'code': 'DOP', 'exchange_rate': 57.0},
            {'name': 'Central African CFA Franc', 'code': 'XAF', 'exchange_rate': 570.0},
            {'name': 'Uzbekistani Som', 'code': 'UZS', 'exchange_rate': 12000.0},
            {'name': 'Bahraini Dinar', 'code': 'BHD', 'exchange_rate': 0.38},
            {'name': 'Yemeni Rial', 'code': 'YER', 'exchange_rate': 250.0},
            {'name': 'Kazakhstan Tenge', 'code': 'KZT', 'exchange_rate': 425.0},
            {'name': 'Armenian Dram', 'code': 'AMD', 'exchange_rate': 510.0},
            {'name': 'Turkish Lira', 'code': 'TRY', 'exchange_rate': 8.7},
            {'name': 'Kuwaiti Dinar', 'code': 'KWD', 'exchange_rate': 0.3},
            {'name': 'Burundian Franc', 'code': 'BIF', 'exchange_rate': 2700.0},
            {'name': 'Georgian Lari', 'code': 'GEL', 'exchange_rate': 3.3},
            {'name': 'Haitian Gourde', 'code': 'HTG', 'exchange_rate': 106.0},
            {'name': 'Ethiopian Birr', 'code': 'ETB', 'exchange_rate': 42.0},
            {'name': 'Lithuanian Litas', 'code': 'LTL', 'exchange_rate': 3.1},
            {'name': 'Nepalese Rupee', 'code': 'NPR', 'exchange_rate': 119.0},
            {'name': 'Afghan Afghani', 'code': 'AFN', 'exchange_rate': 86.0},
            {'name': 'Bolivian Bolíviano', 'code': 'BOB', 'exchange_rate': 6.9},
            {'name': 'Zambian Kwacha', 'code': 'ZMW', 'exchange_rate': 23.0},
            {'name': 'Cambodian Riel', 'code': 'KHR', 'exchange_rate': 4100.0},
            {'name': 'Costa Rican Colón', 'code': 'CRC', 'exchange_rate': 620.0},
            {'name': 'Burmese Kyat', 'code': 'MMK', 'exchange_rate': 1450.0},
            {'name': 'Guatemalan Quetzal', 'code': 'GTQ', 'exchange_rate': 7.8},
            {'name': 'Chilean Peso', 'code': 'CLP', 'exchange_rate': 820.0},
            {'name': 'Rwandan Franc', 'code': 'RWF', 'exchange_rate': 1010.0},
            {'name': 'Zambian Kwacha', 'code': 'ZMW', 'exchange_rate': 23.0},
            {'name': 'Iraqi Dinar', 'code': 'IQD', 'exchange_rate': 1450.0},
            {'name': 'Paraguayan Guarani', 'code': 'PYG', 'exchange_rate': 7000.0},
            {'name': 'Malagasy Ariary', 'code': 'MGA', 'exchange_rate': 4200.0},
            {'name': 'Namibian Dollar', 'code': 'NAD', 'exchange_rate': 14.0},
            {'name': 'Lebanese Pound', 'code': 'LBP', 'exchange_rate': 1500.0},
            {'name': 'Sudanese Pound', 'code': 'SDG', 'exchange_rate': 455.0},
            {'name': 'Mozambican Metical', 'code': 'MZN', 'exchange_rate': 71.0},
            {'name': 'Macau Pataca', 'code': 'MOP', 'exchange_rate': 8.0},
            {'name': 'Libyan Dinar', 'code': 'LYD', 'exchange_rate': 4.52},
            {'name': 'Syrian Pound', 'code': 'SYP', 'exchange_rate': 2500.0},
            {'name': 'Congolese Franc', 'code': 'CDF', 'exchange_rate': 2000.0},
            {'name': 'Burundian Franc', 'code': 'BIF', 'exchange_rate': 2700.0},
            {'name': 'Djiboutian Franc', 'code': 'DJF', 'exchange_rate': 177.5},
            {'name': 'Maldivian Rufiyaa', 'code': 'MVR', 'exchange_rate': 15.42},
            {'name': 'Belize Dollar', 'code': 'BZD', 'exchange_rate': 2.0},
            {'name': 'Samoan Tala', 'code': 'WST', 'exchange_rate': 2.56},
            {'name': 'Namibian Dollar', 'code': 'NAD', 'exchange_rate': 14.0},
            {'name': 'Solomon Islands Dollar', 'code': 'SBD', 'exchange_rate': 8.13},
            {'name': 'Belarusian Ruble', 'code': 'BYN', 'exchange_rate': 2.5},
            {'name': 'Malawian Kwacha', 'code': 'MWK', 'exchange_rate': 950.0},
            {'name': 'Laotian Kip', 'code': 'LAK', 'exchange_rate': 10100.0},
            {'name': 'Congolese Franc', 'code': 'CDF', 'exchange_rate': 2000.0},
            {'name': 'Bosnian Convertible Mark', 'code': 'BAM', 'exchange_rate': 1.6},
            {'name': 'Angolan Kwanza', 'code': 'AOA', 'exchange_rate': 650.0},
            {'name': 'Dominican Peso', 'code': 'DOP', 'exchange_rate': 57.0},
            {'name': 'Armenian Dram', 'code': 'AMD', 'exchange_rate': 510.0},
            {'name': 'Central African CFA Franc', 'code': 'XAF', 'exchange_rate': 570.0},
        ]

        for index, currency_data in enumerate(currencies_data, start=1):
            name = currency_data['name']
            code = currency_data['code']
            exchange_rate = currency_data['exchange_rate']

            Currency.objects.get_or_create(**currency_data)
        
        self.stdout.write(self.style.SUCCESS('Валюты успешно созданы'))
